site_name: "graphium"
site_description: "Graphium: Scaling molecular GNNs to infinity."
site_url: "https://github.com/datamol-io/graphium"
repo_url: "https://github.com/datamol-io/graphium"
repo_name: "valence-discovery/graphium"
copyright: Copyright 2020 - 2023 datamol.io

remote_branch: "gh-pages"
use_directory_urls: false
docs_dir: "docs"

nav:
  - Overview: index.md
  - API:
    - graphium.nn:
      - graphium.nn: api/graphium.nn/graphium.nn.md
      - graphium.nn.architectures: api/graphium.nn/architectures.md
      - graphium.nn.encoders: api/graphium.nn/encoders.md
      - graphium.nn.pyg_layers: api/graphium.nn/pyg_layers.md
    - graphium.features: api/graphium.features.md
    - graphium.trainer: api/graphium.trainer.md
    - graphium.data: api/graphium.data.md
    - graphium.utils: api/graphium.utils.md
    - graphium.config: api/graphium.config.md
    - graphium.ipu: api/graphium.ipu.md
    - graphium.visualization: api/graphium.visualization.md
  - Tutorials:
    - feature_processing:
      - Add new positional encoding: tutorials/feature_processing/add_new_positional_encoding.ipynb
      - Convert CSV to Parquet files: tutorials/feature_processing/csv_to_parquet.ipynb
      - Timing parallel processing: tutorials/feature_processing/timing_parallel.ipynb
    - gnn_layers:
      - Add new gnn layers: tutorials/gnn/add_new_gnn_layers.ipynb
      - Making GNN networks: tutorials/gnn/making_gnn_networks.ipynb
      - Using GNN layers: tutorials/gnn/using_gnn_layers.ipynb
    - model_training:
      - Simple Molecular Model: tutorials/model_training/simple-molecular-model.ipynb
      - Training on IPU: tutorials/model_training/ipu_training.ipynb
      - Chosing the right parallelization: tutorials/basics/choosing_parallelization.ipynb
  - Design: design.md
  - Datasets: datasets.md
  - Pretrained Models: pretrained_models.md
  - Contribute: contribute.md
  - License: license.md
  - CLI: cli_references.md

theme:
  name: material
  palette:
    primary: red
    accent: indigo
  features:
    - navigation.tabs
    - navigation.expand
  favicon: images/logo.png
  logo: images/logo.png

extra_css:
  - _assets/css/custom.css

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - admonition
  - markdown_include.include
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.details
  - mkdocs-click
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      watch:
        - graphium/
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("docs")
            - sys.path.append("graphium")
          selection:
            new_path_syntax: yes
          rendering:
            show_root_heading: yes
            heading_level: 3
          options:
            show_source: false
  - mkdocs-jupyter:
      execute: False
