site_name: "goli"
site_description: "A deep learning library focused on graph representation learning for real-world chemical tasks."
site_url: "https://github.com/invivoai/goli"
repo_url: "https://github.com/invivoai/goli"
repo_name: "invivoai/goli"
copyright: Copyright 2020 - 2021 InvivoAI

remote_branch: "privpage"
use_directory_urls: false
docs_dir: "docs"

nav:
  - Overview: index.md
  - Examples:
      - Using GNN layers: examples/basics/using_gnn_layers.ipynb
      - Implementing GNN layers: examples/basics/implementing_gnn_layers.ipynb
      - Making GNN networks: examples/basics/making_gnn_networks.ipynb
  - API:
    - goli.nn: api/goli.nn.md
    - goli.features: api/goli.features.md
    - goli.trainer: api/goli.trainer.md
    # - goli.cli: api/goli.cli.md
    - goli.utils: api/goli.utils.md
    # - goli.data_parser: api/goli.data_parser.md

theme:
  name: material
  palette:
    primary: teal
    accent: purple
  features:
    # - navigation.instant
    - navigation.expand

extra_css:
  - _assets/css/custom.css

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - admonition
  - markdown_include.include
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      watch:
        - goli/
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("docs")
            - sys.path.append("goli")
          selection:
            new_path_syntax: yes
          rendering:
            show_root_heading: yes
            heading_level: 3
  - mkdocs-jupyter:
      execute: False
      # kernel_name: python3
