site_name: "goli"
site_description: "A deep learning library focused on graph representation learning for real-world chemical tasks."
site_url: "https://github.com/valence-discovery/goli"
repo_url: "https://github.com/valence-discovery/goli"
repo_name: "valence-discovery/goli"
copyright: Copyright 2020 - 2023 Valence Discovery

remote_branch: "gh-pages"
use_directory_urls: false
docs_dir: "docs"

nav:
  - Overview: index.md
  - Tutorials:
    - basics:
      - Using GNN layers: tutorials/basics/using_gnn_layers.ipynb
      - Implementing GNN layers: tutorials/basics/implementing_gnn_layers.ipynb
      - Making GNN networks: tutorials/basics/making_gnn_networks.ipynb
      - Convert CSV to Parquet files: tutorials/basics/csv_to_parquet.ipynb
      - Reading Parquet files: tutorials/basics/parquet_reader.ipynb
    - model_training:
      - Simple Molecular Model: tutorials/model_training/simple-molecular-model.ipynb
      - Training on IPU: tutorials/model_training/ipu_training.ipynb
      - Chosing the right parallelization: tutorials/basics/choosing_parallelization.ipynb
  - Design: design.md
  - Datasets: datasets.md
  - Pretrained Models: pretrained_models.md
  - Contribute: contribute.md
  - License: license.md
  - API:
    - goli.nn:
      - goli.nn: api/goli.nn/goli.nn.md
      - goli.nn.architectures: api/goli.nn/architectures.md
      - goli.nn.encoders: api/goli.nn/encoders.md
      - goli.nn.pyg_layers: api/goli.nn/pyg_layers.md
      - goli.nn.dgl_layers: api/goli.nn/dgl_layers.md
    - goli.features: api/goli.features.md
    - goli.trainer: api/goli.trainer.md
    - goli.data: api/goli.data.md
    - goli.utils: api/goli.utils.md
    - goli.config: api/goli.config.md
    - goli.ipu: api/goli.ipu.md
    - goli.visualization: api/goli.visualization.md
  - CLI: cli_references.md

theme:
  name: material
  palette:
    primary: red
    accent: indigo
  features:
    - navigation.expand
  favicon: images/logo.png
  logo: images/logo.png

extra_css:
  - _assets/css/custom.css

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - admonition
  - markdown_include.include
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.details
  - mkdocs-click
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      watch:
        - goli/
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("docs")
            - sys.path.append("goli")
          selection:
            new_path_syntax: yes
          rendering:
            show_root_heading: yes
            heading_level: 3
          options:
            show_source: false
  - mkdocs-jupyter:
      execute: False
