gin:
  layer_class: gin
  edge_features: False

gcn:
  layer_class: gcn
  edge_features: False

gat-4:
  layer_class: gat
  num_heads: 4
  edge_features: False

gat-8:
  layer_class: gat
  num_heads: 8
  edge_features: False

gat-16:
  layer_class: gat
  num_heads: 16
  edge_features: False

gated-gcn:
  layer_class: gated-gcn
  edge_features: True
  in_dim_edges: 14

mpnn-sum:
  layer_class: pna-msgpass
  edge_features: False
  avg_d: null
  aggregators: "sum"
  scalers: "identity"
  towers: 1

mpnn-max:
  layer_class: pna-msgpass
  edge_features: False
  avg_d: null
  aggregators: "max"
  scalers: "identity"
  towers: 1

mpnn-e-sum:
  layer_class: pna-msgpass
  edge_features: True
  in_dim_edges: 16
  avg_d: null
  aggregators: "sum"
  scalers: "identity"
  towers: 1

mpnn-e-max:
  layer_class: pna-msgpass
  edge_features: True
  in_dim_edges: 16
  avg_d: null
  aggregators: "max"
  scalers: "identity"
  towers: 1

pna:
  layer_class: pna-msgpass
  edge_features: False
  avg_d:
    log: 1
  aggregators: "mean max min std"
  scalers: "identity amplification attenuation"
  towers: 1

pna-no-scaler:
  layer_class: pna-msgpass
  edge_features: False
  avg_d:
    log: 1
  aggregators: "mean max min std"
  scalers: "identity"
  towers: 1

pna-e: 
  layer_class: pna-msgpass
  edge_features: True
  in_dim_edges: 16
  avg_d:
    log: 1
  aggregators: "mean max min std"
  scalers: "identity amplification attenuation"
  towers: 1

pna-e-no-scaler: 
  layer_class: pna-msgpass
  edge_features: True
  in_dim_edges: 16
  avg_d:
    log: 1
  aggregators: "mean max min std"
  scalers: "identity"
  towers: 1


mpnn4-sum:
  layer_class: pna-msgpass
  edge_features: False
  avg_d: null
  aggregators: "sum"
  scalers: "identity"
  towers: 4

mpnn4-max:
  layer_class: pna-msgpass
  edge_features: False
  avg_d: null
  aggregators: "max"
  scalers: "identity"
  towers: 4

mpnn4-e-sum:
  layer_class: pna-msgpass
  edge_features: True
  in_dim_edges: 16
  avg_d: null
  aggregators: "sum"
  scalers: "identity"
  towers: 4

mpnn4-e-max:
  layer_class: pna-msgpass
  edge_features: True
  in_dim_edges: 16
  avg_d: null
  aggregators: "max"
  scalers: "identity"
  towers: 4

pna4:
  layer_class: pna-msgpass
  edge_features: False
  avg_d:
    log: 1
  aggregators: "mean max min std"
  scalers: "identity amplification attenuation"
  towers: 4

pna4-no-scaler:
  layer_class: pna-msgpass
  edge_features: False
  avg_d:
    log: 1
  aggregators: "mean max min std"
  scalers: "identity"
  towers: 4

pna4-e: 
  layer_class: pna-msgpass
  edge_features: True
  in_dim_edges: 16
  avg_d:
    log: 1
  aggregators: "mean max min std"
  scalers: "identity amplification attenuation"
  towers: 4

pna4-e-no-scaler: 
  layer_class: pna-msgpass
  edge_features: True
  in_dim_edges: 16
  avg_d:
    log: 1
  aggregators: "mean max min std"
  scalers: "identity"
  towers: 4

pna-conv:
  layer_class: pna-conv
  edge_features: False
  avg_d:
    log: 1
  aggregators: "mean max min std"
  scalers: "identity amplification attenuation"
  posttrans_layers: 1

pna-conv2:
  layer_class: pna-conv
  edge_features: False
  avg_d:
    log: 1
  aggregators: "sum mean max min std"
  scalers: "identity"
  posttrans_layers: 1

pna-conv3:
  layer_class: pna-conv
  edge_features: False
  avg_d:
    log: 1
  aggregators: "sum min max"
  scalers: "identity"
  posttrans_layers: 1


