constants:
  device: 'cuda:0'
  seed: 111
  upload_to_aws: false
  exp_name: 'no-name'
  ignore_train_error: false
  config_gnns: 'goli/expts/config_gnns.yaml'


datasets:
  y_col: ['score']
  smiles_cols: SMILES
  train:
    data_dir: &data_dir 'data/micro_ZINC/'
    nrows: null
    filename: train
  val:
    data_dir: *data_dir
    nrows: null
    filename: val
  test:
    data_dir: *data_dir
    nrows: null
    filename: test


model:
  layer_name: pna-e  # gcn, gin, pna-e, gat-4, mpnn-max, pna-simple3 ...
  gnn_architecture: resnet  # skip-concat, resnet, resnet-residualweights
  gnn_kwargs:
    hidden_dim: 32
    hidden_depth: 4
    last_activation: relu
    dropout: 0.25
    batch_norm: True
    pooling: sum
    skip_steps: 2
    intermittent_pooling: none # none, sum, mean, max, std, s2s, sum_max, sum_mean_max, ...
  lnn_kwargs:
    hidden_dim: 32
    hidden_depth: 2
    last_activation: sigmoid
    dropout: 0.25
    batch_norm: False


model_wrapper:
  loss_fun: mse
  lr: 1.e-3
  batch_size: 64
  siamese: False
  num_workers: 0
  target_nan_mask: 0 # null: no mask, 0: 0 mask, ignore: ignore nan values from loss


metrics:

  metrics_on_progress_bar: [mae] #, auroc-greater-0.5]

  thresholds: &thresholds
    above_th: &above_th True
    ths: &ths [0.5]
    th_on_pred: &th_on_pred True
    th_on_target: &th_on_target True

  metrics_dict:
    mae:
      threshold: null
    f1:
      # class_reduction: micro
      threshold: *thresholds
    precision:
      # class_reduction: micro
      threshold: *thresholds
    # auroc:
    #   pos_label: 1
    #   threshold:
    #     above_th: *above_th
    #     ths: *ths
    #     th_on_pred: False
    #     th_on_target: *th_on_target


training:
  early_stopping:
    monitor: &monitor val_loss
    min_delta: 0
    patience: 10
    mode: &mode min
  model_checkpoint:
    filepath: models_checkpoints/model.ckpt
    monitor: *monitor
    mode: *mode
    save_top_k: 1
    period: 1
  trainer:
    max_epochs: 12
    min_epochs: 5
    