# @package _global_

architecture:
  task_heads:
    qm9:
      task_level: graph
      out_dim: 19
      hidden_dims: 128
      depth: 2
      activation: relu
      last_activation: none
      dropout: ${architecture.pre_nn.dropout}
      normalization: ${architecture.pre_nn.normalization}
      last_normalization: "none"
      residual_type: none
    tox21:
      task_level: graph
      out_dim: 12
      hidden_dims: 64
      depth: 2
      activation: relu
      last_activation: none
      dropout: ${architecture.pre_nn.dropout}
      normalization: ${architecture.pre_nn.normalization}
      last_normalization: "none"
      residual_type: none
    zinc:
      task_level: graph
      out_dim: 3
      hidden_dims: 32
      depth: 2
      activation: relu
      last_activation: none
      dropout: ${architecture.pre_nn.dropout}
      normalization: ${architecture.pre_nn.normalization}
      last_normalization: "none"
      residual_type: none

predictor:
  metrics_on_progress_bar:
    qm9: ["mae"]
    tox21: ["auroc"]
    zinc: ["mae"]
  loss_fun:
    qm9: mae_ipu
    tox21: bce_logits_ipu
    zinc: mae_ipu

metrics:
  qm9: &qm9_metrics
    - name: mae
      metric: mae_ipu
      target_nan_mask: null
      multitask_handling: flatten
      threshold_kwargs: null
    - name: pearsonr
      metric: pearsonr_ipu
      threshold_kwargs: null
      target_nan_mask: null
      multitask_handling: mean-per-label
    - name: r2_score
      metric: r2_score_ipu
      target_nan_mask: null
      multitask_handling: mean-per-label
      threshold_kwargs: null
  tox21:
    - name: auroc
      metric: auroc_ipu
      task: binary
      multitask_handling: mean-per-label
      threshold_kwargs: null
    - name: avpr
      metric: average_precision_ipu
      task: binary
      multitask_handling: mean-per-label
      threshold_kwargs: null
    - name: f1 > 0.5
      metric: f1
      multitask_handling: mean-per-label
      target_to_int: True
      num_classes: 2
      average: micro
      threshold_kwargs: &threshold_05
        operator: greater
        threshold: 0.5
        th_on_preds: True
        th_on_target: True
    - name: precision > 0.5
      metric: precision
      multitask_handling: mean-per-label
      average: micro
      threshold_kwargs: *threshold_05
  zinc: *qm9_metrics