---
project_name: &project_name neurips2023_sweeps
model_config: "expts/neurips2023_configs/config_small_mpnn.yaml"

sweep_cfg:
  method: random
  name: *project_name
  program: main_neurips_sweep.py

  metric:
    goal: "minimize"
    name: "loss/test"

  parameters:
    gnn_depth:
      model_config_path:
      - architecture.gnn.depth
      distribution: int_uniform
      min: 2
      max: 10
    gnn_dropout:
      model_config_path:
      - architecture.gnn.dropout
      distribution: uniform
      max: 0.6
      min: 0.0
    lr:
      model_config_path:
      - predictor.optim_kwargs.lr
      distribution: log_uniform_values
      min: 1.0e-05
      max: 1.0e-03
    max_epochs:
      model_config_path:
      - trainer.trainer.max_epochs
      values:
      - 2
      - 4
