data:
  module_type: "DGLFromSmilesDataModule"
  args:
    df_path: null  # could be set from the CLI. Ideally config files does not have paths.
    cache_data_path: null  # could be set from the CLI. Ideally config files does not have paths.

    smiles_col: "SMILES"
    label_cols: ["SA"]
    split_val: 0.2
    split_test: 0.2
    split_seed: 19

    batch_size_training: 16
    batch_size_inference: 16

    featurization:
      atom_property_list_float: []
      atom_property_list_onehot: ["atomic-number", "degree"]
      edge_property_list: ["in-ring", "bond-type-onehot"]
      add_self_loop: false
      use_bonds_weights: false
      explicit_H: false
