data:
  module_type: "DGLFromSmilesDataModule"
  args:
    # df_path: null
    # cache_data_path: null

    smiles_col: "SMILES"
    label_cols: ["SA"]
    split_val: 0.2
    split_test: 0.2
    split_seed: 19

    train_val_batch_size: 16
    test_batch_size: 16

    featurization:
      atom_property_list_float: []
      atom_property_list_onehot: ["atomic-number", "degree"]
      edge_property_list: ["ring", "bond-type-onehot"]
      add_self_loop: false
      use_bonds_weights: false
      explicit_H: false
