name: Lint

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "*"

jobs:
  lint-source-code:
    name: Lint
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install black
        run: |
          pip install black==20.8b1

      - name: Lint
        run: |
          black --check .
