name: test-ipu

on:
  workflow_call:

jobs:
  test-ipu:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        pytorch-version: ["1.13"]
        pytest-args: [{name: ipu, cmd: "--verbose --durations=10 -n auto -cov=graphium --cov-fail-under=0 --cov-report xml:coverage_4.xml --cov-report term -m 'ipu'"}]

    runs-on: "ubuntu-latest"
    timeout-minutes: 30

    defaults:
      run:
        shell: bash -l {0}

    name: |
        ${{ matrix.pytest-args.name }} - 
        python=${{ matrix.python-version }} -
        pytorch=${{ matrix.pytorch-version }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Download Poplar SDK
        run: |
          wget -O 'poplar_sdk-ubuntu_20_04-3.2.0-7cd8ade3cd.tar.gz' 'https://downloads.graphcore.ai/direct?package=poplar-poplar_sdk_ubuntu_20_04_3.2.0_7cd8ade3cd-3.2.0&file=poplar_sdk-ubuntu_20_04-3.2.0-7cd8ade3cd.tar.gz'
          tar -xzf poplar_sdk-ubuntu_20_04-3.2.0-7cd8ade3cd.tar.gz
      - name: Install Poplar SDK
        run: |
          pip install poplar_sdk-ubuntu_20_04-3.2.0+1277-7cd8ade3cd/poptorch-3.2.0+109946_bb50ce43ab_ubuntu_20_04-cp38-cp38-linux_x86_64.whl

      - name: Activate SDK + Install Requirements
        run: |
          # Enable Poplar SDK (including Poplar and PopART)
          source poplar_sdk-ubuntu_20_04-3.2.0+1277-7cd8ade3cd/enable

          # Install the IPU specific and graphium requirements
          PACKAGE_NAME=pytorch pip install -r requirements_ipu.txt
          pip install -r lightning.txt
      - name: Install Graphium
        run: |
          # Install Graphium in dev mode
          pip install --no-deps -e .

      - name: Test CLI
        run: graphium --help
