name: test

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "*"
      - "!privpage"

jobs:
  test:
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    env:
      ANACONDA_USER_TOKEN: ${{ secrets.INVIVOAI_ANACONDA_USER_BOT_TOKEN }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          use-mamba: true
          activate-environment: goli

      - name: Install Dependencies
        run: mamba env update -f env.yml

      - name: Install library
        run: python -m pip install .

      - name: Run tests
        run: pytest

      - name: Test CLI
        run: goli --help

      - name: Test building the doc
        run: |
          # Build and serve the doc
          mkdocs build

      - name: Deploy the doc
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          # Get the privpage branch
          git fetch origin privpage

          # Build and serve the doc
          mkdocs gh-deploy
