name: test

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
        pytorch-version: ["1.12"]

    runs-on: "ubuntu-latest"
    timeout-minutes: 30

    defaults:
      run:
        shell: bash -l {0}

    name: |
      python=${{ matrix.python-version }} -
      pytorch=${{ matrix.pytorch-version }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup Mamba
        uses: mamba-org/provision-with-micromamba@v14
        with:
          environment-file: env.yml
          environment-name: goli
          extra-specs: |
            python=${{ matrix.python-version }}
            pytorch=${{ matrix.pytorch-version }}
          cache-downloads: true
          cache-env: true
          channel-priority: strict

      - name: Install library
        run: python -m pip install --no-deps .

      - name: Run tests
        run: pytest

      - name: Test CLI
        run: goli --help

      - name: Test building the doc
        run: mkdocs build

      - name: Deploy the doc
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          # Get the privpage branch
          git fetch origin gh-pages

          # Build and serve the doc
          mkdocs gh-deploy --force
