name: test-ipu

on:
  workflow_call:

jobs:
  test-ipu:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]
        pytorch-version: ["1.13"]

    runs-on: "ubuntu-latest"
    timeout-minutes: 300

    defaults:
      run:
        shell: bash -l {0}

    name: |
        poptorch_env - 
        python=${{ matrix.python-version }} -
        pytorch=${{ matrix.pytorch-version }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Activate SDK + Install Requirements
        run: |
          python3 -m pip install --upgrade pip
          pip install https://downloads.graphcore.ai/direct?package=poplar-poplar_sdk_ubuntu_20_04_3.3.0_208993bbb7-3.3.0&file=poplar_sdk-ubuntu_20_04-3.3.0-208993bbb7.tar.gz
          # Enable Poplar SDK (including Poplar and PopART)
          source poplar_sdk-ubuntu_20_04-3.3.0-208993bbb7/enable

          # Install the IPU specific and graphium requirements
          pip install -r requirements_ipu.txt
          # Install Graphium in dev mode
          python -m pip install --no-deps -e .

      - name: Run tests
        run: pytest 

      - name: Test CLI
        run: graphium --help

      - name: Test building the doc
        run: mkdocs build
