name: test-ipu

on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
    branches:
      - "*"
      - "!gh-pages"
  schedule:
    - cron: "0 4 * * MON"

jobs:
  test-ipu:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]
        pytorch-version: ["2.0"]

    runs-on: "ubuntu-latest"
    timeout-minutes: 300

    defaults:
      run:
        shell: bash -l {0}

    name: |
        poptorch_env - 
        python=${{ matrix.python-version }} -
        pytorch=${{ matrix.pytorch-version }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Activate SDK + Install Requirements
        run: |
          python3 -m pip install --upgrade pip
          pip install https://downloads.graphcore.ai/direct?package=poplar-poplar_sdk_ubuntu_20_04_3.3.0_208993bbb7-3.3.0&file=poplar_sdk-ubuntu_20_04-3.3.0-208993bbb7.tar.gz
          # Enable Poplar SDK (including Poplar and PopART)
          source poplar_sdk-ubuntu_20_04-3.3.0-208993bbb7/enable

          # Install the IPU specific and graphium requirements
          pip install -r requirements_ipu.txt
          # Install Graphium in dev mode
          python -m pip install --no-deps -e .

      - name: Run tests
        run: python3 -m pytest -m 'not skip_ipu'

      - name: Test CLI
        run: graphium --help

  codecov:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        pytorch-version: ["1.13"]
    runs-on: "ubuntu-latest"
    timeout-minutes: 30

    defaults:
      run:
        shell: bash -l {0}
    
    name: codecov
    needs: [test-ipu]
    steps:
      - name: Codecov Upload
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
          verbose: false
          env_vars: ${{ matrix.python-version }},${{ matrix.pytorch-version }}